[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "./scripts/check-db.ts && ./scripts/railway-start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

[variables]
PORT = "8080"
NODE_ENV = "production"